name: Integration CI
#workflow
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Integration Works
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --prefix ./backend/
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '4.2'

    - name: create .env file 
      run: |
        cd backend && ls && touch .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "mongodb://localhost:27017/test" >> .env
        echo "AMADEUS_CLIENT_ID=${{ secrets.AMADEUS_CLIENT_ID }}" >> .env
        echo "AMADEUS_CLIENT_SECRET=${{ secrets.AMADEUS_CLIENT_SECRET }}" >> .env
        echo  "CHATGPT_KEY=TEST" >> .env
        echo "env file created"
        cat .env

    - name: Run Tests
      if: ${{ failure() == false }}
      run: npm test --prefix ./backend/

    - name: Confirm tests success
      if: ${{ success() }}
      run: echo "All tests passed successfully!"