name: Packer Validation
#workflow
on:
  pull_request:
    branches:
     - main

jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: ls

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        
      - name: Navigate to the backend
        run: cd backend

      - name: Initialize Packer
        run: packer init .
       
      - name: Packer fmt
        run: packer fmt -check ami.us-east-1.pkr.hcl

      - name: Packer validate
        run: packer validate ami.us-east-1.pkr.hcl