name: Packer Validation
#workflow
on:
  pull_request:
    branches:
     - main

jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: ls

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        
      - name: list files
        run: |
          ls -a
          current_directory=$(pwd)      
          echo `pwd`

      - name: Navigate to the backend
        run: |
           cd backend
           echo `pwd`   
           echo `ls`
           
      - name: Check if Packer file exists
        run: |
             if [ -f "ami.us-east-1.pkr.hcl" ]; then
               echo "Packer file found."
             else
               echo "Packer file not found. Check the file location."
               exit 1
             fi

      - name: Initialize Packer
        run: packer init .
       
      - name: Packer fmt
        run: packer fmt -check ami.us-east-1.pkr.hcl

      - name: Packer validate
        run: packer validate ami.us-east-1.pkr.hcl