name: Packer Validation
#workflow
on:
  pull_request:
    branches:
     - main

jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: ls

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        

      - name: Initialize Packer
        run: packer init .
       
      - name: Packer fmt
        run: packer fmt -check ami.us-east-1.pkr.hcl

      - name: Packer validate
        run: packer validate ami.us-east-1.pkr.hcl

      - name: Build AMI
        env:
          AWS_REGION : ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: packer build ami.us-east-1.pkr.hcl
          
      - name: Check for errors
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Packer template formatting and validation succeeded."
          else
            echo "Packer template formatting or validation failed."
            exit 1
          fi

      - name: Retrieve Latest AMI ID
        run: |
            latest_ami=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
            echo "latest ami is $latest_ami"
    
      - name: Create new Launch Template version
        run: |
            latest_ami=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
            aws ec2 create-launch-template-version \
              --launch-template-name ${{ secrets.TEMPLATE_NAME }} \
              --region ${{ secrets.AWS_REGION }} \
              --source-version 1 \
              --launch-template-data "{\"ImageId\": \"$latest_ami\"}"